#!/usr/bin/env python3
"""Parse process tree JSON and display CPU usage statistics.

Reads the .processtree.json file generated by process_tree.py and displays
top processes by CPU usage, formatted for user selection.

Usage:
    python parse_processtree.py <json_path> [--top N] [--min-cpu PCT]

Arguments:
    json_path      Path to .processtree.json file (local or UNC)
    --top N        Show top N processes (default: 15)
    --min-cpu PCT  Only show processes with CPU% >= PCT (default: 0)

Exit codes:
    0  success — process list displayed
    1  failure — JSON parsing error
"""

import json
import sys
import argparse
from pathlib import Path


def format_process_tree(processes, top_n=15, min_cpu=0):
    """Format processes as a tree with indentation based on parent-child relationships."""

    # Filter by minimum CPU
    filtered = [p for p in processes if p.get('cpuPct', 0) >= min_cpu]

    # Sort by CPU percentage descending
    filtered.sort(key=lambda x: x.get('cpuPct', 0), reverse=True)

    # Limit to top N
    filtered = filtered[:top_n]

    # Build parent-child map for indentation
    pid_to_proc = {p['pid']: p for p in filtered}

    output = []
    for proc in filtered:
        parent_pid = proc.get('parentPid')
        # Simple indentation: if parent is in our list, indent
        indent = "  " if parent_pid in pid_to_proc else ""

        name = proc.get('name', 'Unknown')
        pid = proc.get('pid')
        cpu_pct = proc.get('cpuPct', 0)
        # ProcessTree (Global.dll) emits the key "cpuMSec" (see PerfViewCommands.md);
        # accept the legacy "cpuMs" as a fallback.
        cpu_ms = proc.get('cpuMSec', proc.get('cpuMs', 0))

        line = f"{indent}{cpu_pct:.2f}%  {name}  (pid={pid}, {cpu_ms}ms, parent={parent_pid})"
        output.append(line)

    return output


def main():
    parser = argparse.ArgumentParser(
        description="Parse process tree JSON and display CPU usage statistics"
    )
    parser.add_argument("json_path", help="Path to .processtree.json file")
    parser.add_argument("--top", type=int, default=15, help="Show top N processes (default: 15)")
    parser.add_argument("--min-cpu", type=float, default=0, help="Minimum CPU%% to display (default: 0)")
    parser.add_argument("--json-output", action="store_true", help="Output as JSON instead of formatted text")

    args = parser.parse_args()

    json_path = args.json_path
    # Fix UNC paths: ensure they start with \\ (not single \)
    if json_path.startswith("\\") and not json_path.startswith("\\\\"):
        json_path = "\\" + json_path

    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            # strict=False: ProcessTree/Global.dll can emit raw control chars
            # (e.g. a literal TAB inside a process cmdLine), which the strict
            # JSON parser rejects. Tolerate them rather than failing the run.
            data = json.load(f, strict=False)
    except FileNotFoundError:
        print(f"Error: File not found: {json_path}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in {json_path}: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error reading {json_path}: {e}", file=sys.stderr)
        sys.exit(1)

    processes = data.get('processes', [])

    if not processes:
        print("No processes found in JSON", file=sys.stderr)
        sys.exit(1)

    # Calculate total CPU time (key is "cpuMSec"; "cpuMs" kept as legacy fallback)
    total_cpu_ms = sum(p.get('cpuMSec', p.get('cpuMs', 0)) for p in processes)

    if args.json_output:
        # Output as JSON for programmatic use
        filtered = [p for p in processes if p.get('cpuPct', 0) >= args.min_cpu]
        filtered.sort(key=lambda x: x.get('cpuPct', 0), reverse=True)
        filtered = filtered[:args.top]

        output = {
            'total_cpu_ms': total_cpu_ms,
            'process_count': len(processes),
            'top_processes': filtered
        }
        print(json.dumps(output, indent=2, ensure_ascii=False))
    else:
        # Human-readable output
        print(f"Total CPU time: {total_cpu_ms} ms\n")
        print(f"Process CPU Usage (Top {args.top}):")

        lines = format_process_tree(processes, args.top, args.min_cpu)
        for line in lines:
            print(line)

        print(f"\nTotal {len(processes)} processes with CPU samples")

        # Show process names for easy selection
        filtered = [p for p in processes if p.get('cpuPct', 0) >= args.min_cpu]
        filtered.sort(key=lambda x: x.get('cpuPct', 0), reverse=True)
        filtered = filtered[:args.top]

        process_names = [p.get('name', 'Unknown') for p in filtered]
        print(f"\nProcess names for selection: {', '.join(process_names)}")


if __name__ == "__main__":
    main()
